apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-volume-claim
  labels:
    app: recipes-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

