version: '3.3'

services:

  recipes_db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  user_db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      app_net:
        ipv4_address: 172.16.238.30
    
  recipes_db_adapter:
    build:
      context: ./recipes-db-adapter
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.16.238.40
    depends_on:
      - "recipes_db"
    
  user_db_adapter:
    build:
      context: ./user-db-adapter
    ports:
      - "5001:5001"
    networks:
      app_net:
        ipv4_address: 172.16.238.50
    depends_on:
      - "user_db"
  
  matchservice:
    build: 
      context: ./matchservice
    ports: 
      - "8080:8080"
    networks: 
      app_net:
        ipv4_address: 172.16.238.80
    depends_on:
      - "recipes_db"
  
  food_api:
    build: 
      context: ./food_game_api
    ports: 
      - "30000:30000"
    environment: 
      - BACKEND=172.20.1.4

  food_frontend:
    build: 
      context: ./food-game-frontend
    ports: 
      - "4200:4200"
    depends_on:
      - "food_api"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"