apiVersion: v1
kind: ServiceAccount
metadata:
  name: foodapp-user
  namespace: food-game
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: foodapp-user-secret
  namespace: food-game
  annotations:
    kubernetes.io/service-account.name: foodapp-user
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: food-game
  name: foodapp-role
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: foodapp-role
  namespace: food-game
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: foodapp-user # "name" is case sensitive
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: foodapp-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""

