apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foodgame-pvc
  labels:
    # insert any desired labels to identify your claim
    app: foodgame-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 2Gi

