apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foodgame-pvc
  labels:
    app: foodgame-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

