apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodfrontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodfrontend
  template:
    metadata:
      labels:
        app: foodfrontend
    spec:
      containers:
      - name: foodcontainer
        image: 172.24.4.1:5000/foodfrontend:v3
        imagePullPolicy: Always
        env:
        # Define the environment variable
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: frontend
                # Specify the key associated with the value
                key: BACKEND_URL
        ports:
        - containerPort: 4200
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regsecret       

---
apiVersion: v1
kind: Service
metadata:
  name: "frontend-accesspoint"
  annotations:
    # Create endpoints also if the related pod isn't ready
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 4200
    nodePort: 30004
    targetPort: 4200
  selector:
    app: foodfrontend
