- name: Deleting cluster
  hosts: paaslab-eval
  gather_facts: yes
  tasks:
    - name: Delete namespace food-game
      community.kubernetes.k8s:
        name: food-game
        api_version: v1
        kind: Namespace
        state: absent
