- name: registry-manager
  hosts: localhost
  vars:
    reg: localhost:5000
    certspath: ~/food-game-k8s/registry/certs
  tasks:  
    - name: Building and pushing Recipes api
      docker_image:
        name: '{{reg}}/recipes-db-api'
        source: build
        ca_cert: '{{ certspath }}'
        client_key: '{{ certspath }}'
        client_cert: '{{ certspath }}'
        build:
          path: ~/food-game-k8s/recipes-db-adapter
        state: present
        push: yes

    - name: Building and pushing Matchservice
      docker_image:
        name: '{{reg}}/matchservice'
        source: build
        ca_cert: '{{ certspath }}'
        client_key: '{{ certspath }}'
        client_cert: '{{ certspath }}'
        build:
          path: ~/food-game-k8s/matchservice
        state: present
        push: yes
        
    - name: Building and pushing Users api
      docker_image:
        name: '{{reg}}/users-db-api'
        source: build
        ca_cert: '{{ certspath }}'
        client_key: '{{ certspath }}'
        client_cert: '{{ certspath }}'
        build:
          path: ~/food-game-k8s/user-db-adapter
        state: present
        push: yes

    - name: Building and pushing Foodgame api
      docker_image:
        name: '{{reg}}/foodgame-api'
        source: build
        ca_cert: '{{ certspath }}'
        client_key: '{{ certspath }}'
        client_cert: '{{ certspath }}'
        build:
          path: ~/food-game-k8s/food_game_api
        state: present
        push: yes
    
    - name: Building and pushing Food frontend
      docker_image:
        name: '{{reg}}/foodfrontend'
        source: build
        ca_cert: '{{ certspath }}'
        client_key: '{{ certspath }}'
        client_cert: '{{ certspath }}'
        build:
          path: ~/food-game-k8s/food-game-frontend
        state: present
        push: yes
    

