apiVersion: v1
kind: Service
metadata:
  name: "matchservice-api-accesspoint"
  namespace: food-game
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 8080
  selector:
    app: matchservice-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchservice-api
  namespace: food-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchservice-api
  template:
    metadata:
      labels:
        app: matchservice-api
    spec:
      containers:
      - name: matchcontainer
        image: 172.24.4.1:5000/matchservice
        imagePullPolicy: Always
        env:
          - name: RECIPES_ROUTE
            valueFrom:
              configMapKeyRef:
                name: recipesurl
                key: RECIPES_ROUTE
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regsecret 



